-- ROL
MERGE INTO SYSTEM.PLAYZONEAPP_ROL r
USING (SELECT 1 AS ID, 'admin' AS NOMBRE FROM dual) data
ON (r.ID = data.ID)
WHEN NOT MATCHED THEN
  INSERT (ID, NOMBRE) VALUES (data.ID, data.NOMBRE);

MERGE INTO SYSTEM.PLAYZONEAPP_ROL r
USING (SELECT 2 AS ID, 'public' AS NOMBRE FROM dual) data
ON (r.ID = data.ID)
WHEN NOT MATCHED THEN
  INSERT (ID, NOMBRE) VALUES (data.ID, data.NOMBRE);


-- CATEGORÍAS
MERGE INTO SYSTEM.PLAYZONEAPP_CATEGORIA c
USING (SELECT 1 AS ID, 'Accion' AS NOMBRE FROM dual) data
ON (c.ID = data.ID)
WHEN NOT MATCHED THEN
  INSERT (ID, NOMBRE) VALUES (data.ID, data.NOMBRE);

MERGE INTO SYSTEM.PLAYZONEAPP_CATEGORIA c
USING (SELECT 2 AS ID, 'Free_To_Play' AS NOMBRE FROM dual) data
ON (c.ID = data.ID)
WHEN NOT MATCHED THEN
  INSERT (ID, NOMBRE) VALUES (data.ID, data.NOMBRE);

MERGE INTO SYSTEM.PLAYZONEAPP_CATEGORIA c
USING (SELECT 3 AS ID, 'Carreras' AS NOMBRE FROM dual) data
ON (c.ID = data.ID)
WHEN NOT MATCHED THEN
  INSERT (ID, NOMBRE) VALUES (data.ID, data.NOMBRE);

MERGE INTO SYSTEM.PLAYZONEAPP_CATEGORIA c
USING (SELECT 4 AS ID, 'Mundo_Abierto' AS NOMBRE FROM dual) data
ON (c.ID = data.ID)
WHEN NOT MATCHED THEN
  INSERT (ID, NOMBRE) VALUES (data.ID, data.NOMBRE);

MERGE INTO SYSTEM.PLAYZONEAPP_CATEGORIA c
USING (SELECT 5 AS ID, 'Supervivencia' AS NOMBRE FROM dual) data
ON (c.ID = data.ID)
WHEN NOT MATCHED THEN
  INSERT (ID, NOMBRE) VALUES (data.ID, data.NOMBRE);

MERGE INTO SYSTEM.PLAYZONEAPP_CATEGORIA c
USING (SELECT 6 AS ID, 'Terror' AS NOMBRE FROM dual) data
ON (c.ID = data.ID)
WHEN NOT MATCHED THEN
  INSERT (ID, NOMBRE) VALUES (data.ID, data.NOMBRE);


-- VIDEOJUEGOS (uno por línea para claridad)
MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'League of Legends' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('League of Legends', 'Juego de estrategia y acción en línea multijugador', 0, 100, 2);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'Fortnite' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('Fortnite', 'Juego de batalla real con construcción y supervivencia', 0, 150, 2);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'Apex Legends' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('Apex Legends', 'Juego de disparos en equipo en un mundo futurista', 0, 120, 2);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'GTA V' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('GTA V', 'Juego de crimen en una ciudad abierta', 23990, 50, 1);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'Assassin Creed Valhalla' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('Assassin Creed Valhalla', 'Juego de acción y aventura en la era vikinga', 45990, 30, 1);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'Red Dead Redemption 2' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('Red Dead Redemption 2', 'Juego de aventura y acción en el lejano oeste', 39990, 40, 1);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'F1 2021' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('F1 2021', 'Simulador de carreras de Fórmula 1', 49990, 60, 3);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'Need for Speed: Hot Pursuit' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('Need for Speed: Hot Pursuit', 'Juego de carreras y persecución policial', 29990, 70, 3);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'Mario Kart 8 Deluxe' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('Mario Kart 8 Deluxe', 'Carreras con los personajes de Mario en circuitos locos', 24990, 80, 3);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'The Witcher 3: Wild Hunt' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('The Witcher 3: Wild Hunt', 'Juego de rol en un mundo de fantasía lleno de magia', 49990, 100, 4);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'Minecraft' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('Minecraft', 'Juego de supervivencia y construcción en un mundo abierto de bloques', 29990, 200, 4);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'The Legend of Zelda: Breath of the Wild' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('The Legend of Zelda: Breath of the Wild', 'Aventura de acción en un vasto mundo abierto', 45990, 50, 4);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'Rust' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('Rust', 'Juego de supervivencia en un mundo abierto y hostil', 23990, 60, 5);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'ARK: Survival Evolved' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('ARK: Survival Evolved', 'Sobrevive en una isla llena de dinosaurios', 35990, 45, 5);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'Dont Starve' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('Dont Starve', 'Juego de supervivencia con un toque de horror', 18990, 90, 5);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'Resident Evil 2' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('Resident Evil 2', 'Juego de terror y supervivencia en una ciudad infestada de zombis', 39990, 50, 6);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'Outlast' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('Outlast', 'Juego de terror psicológico en un manicomio abandonado', 19990, 30, 6);

MERGE INTO SYSTEM.PLAYZONEAPP_VIDEOJUEGO v
USING (SELECT 'Phasmophobia' AS NOMBRE FROM dual) data
ON (v.NOMBRE = data.NOMBRE)
WHEN NOT MATCHED THEN
  INSERT (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA_ID)
  VALUES ('Phasmophobia', 'Juego cooperativo de terror en el que cazas fantasmas', 25990, 60, 6);
